// =============================================================
// Shared Zod schemas for the v1 API.
//
//  - RFC 7807 problem-details for every non-2xx response.
//  - Page / paged-list helpers for collection endpoints.
//  - Re-export `z` from @hono/zod-openapi so callers don't have
//    to remember which copy of zod has the `.openapi(...)` method
//    attached.
// =============================================================

import { z } from '@hono/zod-openapi';

export { z };

/** RFC 7807 problem details. Mirrors src/api/middleware/error.ts output. */
export const ProblemDetailsSchema = z
  .object({
    type: z.string().openapi({
      description:
        'A URI reference identifying the problem type. Defaults to "about:blank" for generic problems.',
      example: 'about:blank',
    }),
    title: z.string().openapi({
      description: 'A short, human-readable summary of the problem type.',
      example: 'Bad Request',
    }),
    status: z.number().int().openapi({
      description: 'The HTTP status code generated by the origin server.',
      example: 400,
    }),
    detail: z.string().optional().openapi({
      description: 'A human-readable explanation specific to this occurrence.',
    }),
    instance: z.string().optional().openapi({
      description: 'A URI reference that identifies the specific occurrence.',
      example: '/v1/jobs/J-1234',
    }),
    errors: z
      .array(
        z.object({
          path: z.array(z.union([z.string(), z.number()])),
          message: z.string(),
          code: z.string().optional(),
        }),
      )
      .optional()
      .openapi({
        description: 'Field-level validation errors when status=400 due to a ZodError.',
      }),
  })
  .openapi('ProblemDetails');

export type ProblemDetails = z.infer<typeof ProblemDetailsSchema>;

/** Standard query parameters for list endpoints. */
export const PagingQuerySchema = z.object({
  limit: z
    .string()
    .optional()
    .transform((v) => (v ? Math.max(1, Math.min(500, Number(v))) : 100))
    .openapi({ description: 'Page size. Default 100, max 500.', example: '100' }),
  offset: z
    .string()
    .optional()
    .transform((v) => (v ? Math.max(0, Number(v)) : 0))
    .openapi({ description: 'Row offset, zero-indexed.', example: '0' }),
});

/** Wraps a row schema as `{ data: T[], total, limit, offset }`. */
export function paged<T extends z.ZodTypeAny>(rowSchema: T) {
  return z.object({
    data: z.array(rowSchema),
    total: z.number().int().nonnegative(),
    limit: z.number().int().positive(),
    offset: z.number().int().nonnegative(),
  });
}

/** Standard "id in path" param. */
export const IdParamSchema = z.object({
  id: z.string().min(1).openapi({
    param: { name: 'id', in: 'path' },
    description: 'Entity identifier.',
    example: 'J-100',
  }),
});

/** Standard JSON response wrapper for the OpenAPI `content` field. */
export function jsonContent<T extends z.ZodTypeAny>(schema: T, description: string) {
  return {
    content: { 'application/json': { schema } },
    description,
  };
}

/** Common problem responses for an endpoint. */
export const ProblemResponses = {
  400: jsonContent(ProblemDetailsSchema, 'Validation error'),
  401: jsonContent(ProblemDetailsSchema, 'Unauthorized'),
  403: jsonContent(ProblemDetailsSchema, 'Forbidden'),
  404: jsonContent(ProblemDetailsSchema, 'Not found'),
  409: jsonContent(ProblemDetailsSchema, 'Conflict'),
  500: jsonContent(ProblemDetailsSchema, 'Server error'),
} as const;

/** A loose ISO-8601 datetime string. */
export const IsoDateTime = z
  .string()
  .openapi({ format: 'date-time', example: '2026-05-22T08:00:00.000Z' });

/** YYYY-MM-DD calendar date. */
export const CalendarDate = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/)
  .openapi({ format: 'date', example: '2026-05-22' });
